FreeRTOS/corePKCS11

- test/unit-test/iot_pkcs11_mbedtls_utest.c
Bump up line coverage.
100%: `C_VerifyInit`, `C_DigestInit`
Missing single line for `C_Verify`, specifically [iot_pkcs11_mbedtls.c#L4257](https://github.com/FreeRTOS/FreeRTOS-PKCS/blob/master/source/portable/mbedtls/iot_pkcs11_mbedtls.c#L4257) which can't be reached  unless the _mechanism_ changes _during_ the function call, by some other means. Theoretically unreachable in single-threaded app.
> Test coverage

- source/portable/mbedtls/iot_pkcs11_mbedtls.c
- test/unit-test/iot_pkcs11_mbedtls_utest.c
Bump `iot_pcks11_mbedtls.c` to 97.3% line coverage.
`CKA_EC_PARAMS` attribute size can now be queried by passing `pValue = NULL`
> More test coverage + Fix C_GetAttributeValue to set arg length when arg handle is NULL

- source/portable/mbedtls/core_pkcs11_mbedtls.c
- test/cbmc/proofs/C_DestroyObject/C_DestroyObject_harness.c
- test/cbmc/proofs/C_DestroyObject/Makefile
- test/cbmc/proofs/C_DestroyObject/README.md
- test/cbmc/proofs/C_DestroyObject/cbmc-proof.txt
- test/cbmc/proofs/C_DestroyObject/cbmc-viewer.json
- test/cbmc/proofs/C_DigestFinal/C_DigestFinal_harness.c
- test/cbmc/proofs/C_DigestFinal/Makefile
- test/cbmc/proofs/C_DigestFinal/README.md
- test/cbmc/proofs/C_DigestFinal/cbmc-proof.txt
- test/cbmc/proofs/C_DigestFinal/cbmc-viewer.json
- test/cbmc/proofs/C_DigestInit/C_DigestInit_harness.c
- test/cbmc/proofs/C_DigestInit/Makefile
- test/cbmc/proofs/C_DigestInit/README.md
- test/cbmc/proofs/C_DigestInit/cbmc-proof.txt
- test/cbmc/proofs/C_DigestInit/cbmc-viewer.json
- test/cbmc/proofs/C_DigestUpdate/C_DigestUpdate_harness.c
- test/cbmc/proofs/C_DigestUpdate/Makefile
- test/cbmc/proofs/C_DigestUpdate/README.md
- test/cbmc/proofs/C_DigestUpdate/cbmc-proof.txt
- test/cbmc/proofs/C_DigestUpdate/cbmc-viewer.json
- test/cbmc/stubs/mbedtls_stubs.c
- test/unit-test/core_pkcs11_mbedtls_utest.c
Added CBMC proofs for:
* C_DestroyObject
* C_DigestInit
* C_DigestUpdate
* C_DigestFinal
Added handle value check to C_DestroyObject.
SHA-256 buffer MUST now be 32 bytes, instead of just greater than 32 bytes.
> CBMC: four proofs

- .github/memory_statistics_config.json
- .github/workflows/ci.yml
- .github/workflows/memory_statistics.yml
- docs/doxygen/config.doxyfile
- docs/doxygen/include/size_table.html
- docs/doxygen/pages.dox
Adds a PR check using the memory statistics action from the shared actions repo. 
Also adds a manual workflow for generating size tables.
> Add PR check for doxygen size table

- docs/doxygen/include/size_table.html
- docs/doxygen/pages.dox
- source/portable/mbedtls/core_pkcs11_mbedtls.c
- source/portable/posix/core_pkcs11_pal.c
- source/portable/windows/core_pkcs11_pal.c
- test/CMakeLists.txt
- test/cbmc/include/core_pkcs11_config.h
- test/cbmc/proofs/C_DestroyObject/Makefile
- test/cbmc/proofs/C_GenerateKeyPair/Makefile
- test/cbmc/stubs/core_pkcs11_pal_stubs.c
- test/unit-test/config/core_pkcs11_config.h
- test/unit-test/core_pkcs11_mbedtls_utest.c
Update unit tests.
Provide a PKCS11_PAL_ObjectDestroy implementation for windows and posix.
This change does mean that ports will need to implement this function, and it is no longer optional.
> Remove PKCS11_PAL_ObjectDestroy from mbedtls implementation.

- README.md
- docs/doxygen/include/size_table.html
- docs/doxygen/pages.dox
- lexicon.txt
- source/portable/mbedtls/core_pkcs11_mbedtls.c
- source/portable/posix/core_pkcs11_pal.c
- test/cbmc/proofs/C_CreateObject/C_CreateObject_harness.c
- test/cbmc/proofs/C_CreateObject/Makefile
- test/cbmc/proofs/C_DestroyObject/C_DestroyObject_harness.c
- test/cbmc/proofs/C_DigestFinal/C_DigestFinal_harness.c
- test/cbmc/proofs/C_DigestInit/C_DigestInit_harness.c
- test/cbmc/proofs/C_DigestUpdate/C_DigestUpdate_harness.c
- test/cbmc/proofs/C_FindObjects/C_FindObjects_harness.c
- test/cbmc/proofs/C_FindObjectsFinal/C_FindObjectsFinal_harness.c
- test/cbmc/proofs/C_FindObjectsInit/C_FindObjectsInit_harness.c
- test/cbmc/proofs/C_GenerateKeyPair/C_GenerateKeyPair_harness.c
- test/cbmc/proofs/C_GenerateRandom/C_GenerateRandom_harness.c
- test/cbmc/proofs/C_GetAttributeValue/C_GetAttributeValue_harness.c
- test/cbmc/proofs/C_Sign/C_Sign_harness.c
- test/cbmc/proofs/C_SignInit/C_SignInit_harness.c
- test/cbmc/proofs/C_Verify/C_Verify_harness.c
- test/cbmc/proofs/C_VerifyInit/C_VerifyInit_harness.c
- test/system-test/system-tests/pkcs11_system_test.c
- test/system-test/test-config/core_pkcs11_config.h
- test/system-test/test-config/core_test_pkcs11_config.h
- test/unit-test/config/core_pkcs11_config.h
- test/unit-test/core_pkcs11_mbedtls_utest.c
Adds support for importing a SHA256-HMAC key.
1. Updates System test.
2. Updates unit tests.
3. Updates POSIX PAL for HMAC key support.
> Feature: Import SHA256-HMAC secret Key

- README.md
The intention of this section is to specify the reasons for the creation of corePKCS11, and how it fits in the development process of a product.
> Add a README snippet outlining the purpose of corePKCS11

- test/unit-test/core_pkcs11_mbedtls_utest.c
The macros did not play nicely with TEST_PROTECT.
Also a TEST_PROTECT block is needed around the de-initialization code. 
This fixes cascading failures, and never ending loops when a test fails.
> Fix TEST_PROTECT logic in unit tests.

- source/portable/mbedtls/core_pkcs11_mbedtls.c
MISRA regressions included two unused variables, and one dead PATH (Checking the key type twice).
> Fix MISRA regressions

- docs/doxygen/pages.dox
Fix bug in pages.dox causing memory table section to appear on wrong page.
This makes the documentation's main page consistent with the other libraries.
> Fix doxygen main page generation

- .github/workflows/ci.yml
- source/dependency/3rdparty/mbedtls_utils/mbedtls_error.h
Update the CI workflow to remove dependency on 3rdparty coverage checker action, and instead use the FreeRTOS/CI-CD-Github-Actions repository. Also, update the formatting, doxygen and link verifier checks to use the actions repository.
> Hygiene fixes in CI checks

- source/portable/windows/core_pkcs11_pal.c
Make changes equivalent to POSIX port for AES-CMAC functionality made in PR #97 in the Windows PAL file.
> Add AES-CMAC algorithm support in Windows port

- CHANGELOG.md
- lexicon.txt
- source/include/core_pkcs11_config_defaults.h
This PR fixes the logic of providing backwards comptability support for `PKCS11_MALLOC`, `PKCS11_FREE` and `configPKCS11_DEFAULT_USER_PIN` configuration macros.
> Fix backwards compatibility support for deprecated configs

- docs/doxygen/include/size_table.md
- source/portable/mbedtls/core_pkcs11_mbedtls.c
- test/unit-test/core_pkcs11_mbedtls_utest.c
This commit fixes 2 memory leaks:
1. `C_SignInit` allocates memory which should be released in `C_Sign`.
2. `C_SignInit` needs to call `PKCS11_PAL_GetObjectValueCleanup` to free the  memory allocated in `PKCS11_PAL_GetObjectValue`.
> Fix memory leaks in corePKCS11

- source/include/core_pkcs11_config_defaults.h
In absence of these, the c-sdk demos fail to build with the latest corePKCS11.
> Add default values for configuration macros

- CHANGELOG.md
- docs/doxygen/include/size_table.md
- source/portable/mbedtls/core_pkcs11_mbedtls.c
- test/system-test/system-tests/pkcs11_system_test.c
- test/unit-test/core_pkcs11_mbedtls_utest.c
This PR addresses the following 2 issues:
1. The test `test_CreateObject_RSA` defines a buffer (named `modulus`) of size 257 on the stack: 
```c
CK_BYTE modulus[ 257 ] = { 0 };
```
The test wants to pass the address of second byte in the buffer to the `C_CreateObject` function. The test code was incorrectly using the expression `&modulus + 1` which was resulting in address of the memory right after the buffer. This commits updates the expression to `&modulus[ 1 ]` to correctly use the address of the second byte.
2. This commit also fixes a memory leak by ensuring that the memory allocated in the `C_VerifyInit` is freed in `C_Verify`.
> Fix invalid memory read in system tests

- .github/workflows/ci.yml
- CHANGELOG.md
- test/unit-test/core_pkcs11_mbedtls_utest.c
- test/unit-test/core_pkcs11_utest.c
This PR enables address sanitizer for unit tests and system tests. It also fixes the 2 issues reported by the sanitizer in unit tests:
1. Update `test_IotPkcs11_vAppendSHA256AlgorithmIdentifierSequence` to avoid invalid memory read and add additional asserts to check the function correctly updated the output parameter.
2. Update `test_pkcs11_C_CreateObjectECPrivKeyBadAtt` to correctly pass ointer value.
> Enable address sanitizer for tests in PR checks

- pkcsFilePaths.cmake
- source/dependency/3rdparty/mbedtls_utils/mbedtls_utils.c
- source/dependency/3rdparty/mbedtls_utils/mbedtls_utils.h
Fix the licenses of mbedtls_utils.c and mbedtls_utils.h. Also fix errors in pkcsFilePaths.cmake.
> Fix licenses and windows path

- README.md
- source/include/core_pkcs11_config_defaults.h
Renames references to `master` to `main`
> Rename master to main in docs

- test/cbmc/proofs/prepare.py
`test/cbmc/proofs/prepare.py` is a symlink to a file that no longer exists. Thus it should be removed.
This PR fixes the failure in the release script due to the zip not having a corresponding file since the link has non-existent target.
> Delete broken symlink

- CHANGELOG.md
- docs/doxygen/pages.dox
- manifest.yml
*Description*:
Bump mbedtls submodule to latest 2.28.0 release
> Bump mbedtls submodule to v2.28.0

- source/portable/os/posix/core_pkcs11_pal.c
Whenever corePKCS11 would check for a file it would log that it could not open the file. This is fine since it just means a new file will be needed, though causes confusion when reading logs as it seems to be an error. This rewords it to not seem like an error and reduces to LogDebug.
> Reduce level of log printed for noneexistant file

- test/cbmc/stubs/pkcs11_interface_stubs.c
Verified the CBMC failure with the existing main branch with cbmc 5.50.0. Also verified that this change fixes the problem on MacOS.
> Update pkcs11_interface_stubs to be compatible with CBMC 5.45+

- docs/doxygen/include/size_table.md
- test/mbedtls_integration/mbedtls_integration_test.c
- test/pkcs11_mbedtls_utest/core_pkcs11_mbedtls_config.yml
- test/pkcs11_mbedtls_utest/core_pkcs11_mbedtls_utest.c
- test/wrapper_utest/core_pkcs11_utest.c
- tools/0001-Fix-missing-prototype-warning-when-MBEDTLS_DEPRECATE.patch
- tools/mbedtls.cmake
- tools/mbedtls_configure.sh
- tools/mbedtls_patch.sh
Update mbedtls library to v2.28.1 and v3.2.1.
Adjust build files and tests accordingly.
> Update mbedtls to the latest upstream revisions

- .github/workflows/ci.yml
- .gitmodules
- test/CMakeLists.txt
- test/cbmc/proofs/C_CloseSession/Makefile
- test/cbmc/proofs/C_CreateObject/Makefile
- test/cbmc/proofs/C_DestroyObject/Makefile
- test/cbmc/proofs/C_DigestFinal/Makefile
- test/cbmc/proofs/C_DigestInit/Makefile
- test/cbmc/proofs/C_DigestUpdate/Makefile
- test/cbmc/proofs/C_Finalize/Makefile
- test/cbmc/proofs/C_FindObjects/Makefile
- test/cbmc/proofs/C_FindObjectsFinal/Makefile
- test/cbmc/proofs/C_FindObjectsInit/Makefile
- test/cbmc/proofs/C_GenerateKeyPair/Makefile
- test/cbmc/proofs/C_GenerateRandom/Makefile
- test/cbmc/proofs/C_GetAttributeValue/Makefile
- test/cbmc/proofs/C_GetFunctionList/Makefile
- test/cbmc/proofs/C_GetMechanismInfo/Makefile
- test/cbmc/proofs/C_GetSlotList/Makefile
- test/cbmc/proofs/C_Initialize/Makefile
- test/cbmc/proofs/C_OpenSession/Makefile
- test/cbmc/proofs/C_Sign/Makefile
- test/cbmc/proofs/C_SignInit/Makefile
- test/cbmc/proofs/C_Verify/Makefile
- test/cbmc/proofs/C_VerifyInit/Makefile
Remove mbedtls submodule, update CBMC CI accordingly
Description
-----------
Remove the mbedtls submodule from the dependencies directory and update the CBMC GitHub actions workflow to use cmake to fetch mbedtls when building cbmc proofs.
Checklist:
----------
> Remove mbedtls submodule

- source/portable/mbedtls/core_pkcs11_mbedtls.c
- test/mbedtls_integration/CMakeLists.txt
- test/pkcs11_mbedtls_utest/core_pkcs11_mbedtls_utest.c
Adjust prvAddObjectToList so that it adds or updates as necessary.
Description
-----------
Adjust prvAddObjectToList so that it adds or updates as necessary.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
Fixes #172
> fix: Fix logic in prvAddObjectToList

- source/portable/mbedtls/core_pkcs11_mbedtls.c
Support optional write generated private key to disk
Description
-----------
For use by the fleet provisioning with CSR demo ( see https://github.com/giuspen/aws-iot-device-sdk-embedded-C/tree/GP_fleet_provisioning_with_csr_demo/demos/fleet_provisioning/fleet_provisioning_with_csr ), I would like to support writing key and certificate to disk when the optional macros DOWNLOADED_CERT_WRITE_PATH and GENERATED_PRIVATE_KEY_WRITE_PATH are provided
Checklist:
----------
> [for fleet provisioning with CSR to support write key and certificate to disk] support optional write generated private key

- .github/workflows/ci.yml
- source/core_pkcs11.c
- source/portable/mbedtls/core_pkcs11_mbedtls.c
- source/portable/os/freertos_winsim/core_pkcs11_pal.c
- test/wrapper_utest/core_pkcs11_utest.c
- tools/mbedtls.cmake
Description
-----------
Use MBedTLS 3.5.1 for the corePKCS11 MBedTLS tests
Add some new checks to account for the changes
Wrap certain sections related to crypto operations in config checks
Swap the Windows port to use `WIN32_LEAN_AND_MEAN` and `winsock2.h` for compatibility with mbedtls v3.5.1
Test Steps
-----------
Ran the FreeRTOS-Plus WinSim demos and unit tests in this repository with these changes.
Checklist:
----------
Related Issue
-----------
> Use MBedTLS 3.5.1

- .github/memory_statistics_config.json
- .gitmodules
- manifest.yml
- pkcsFilePaths.cmake
- test/cbmc/proofs/Makefile-project-defines
Description
-----------
Use the pkcs11 repository provided by OASIS instead of the amazon-freertos github organization.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Switch pkcs11 submodule to OASIS repository

- source/core_pkcs11.c
- source/core_pki_utils.c
- source/portable/mbedtls/core_pkcs11_mbedtls.c
- tools/coverity/misra.config
Description
-----------
* Fix rule 18.4 deviations. Not using operators with pointer type.
* Suppress rule 20.5 deviations in misra.config to allow use of undef.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Fix MISRA C 2012 deviations

- .github/.cSpellWords.txt
- .github/workflows/ci.yml
- README.md
- test/CMakeLists.txt
- tools/coverity/README.md
Update coverity version message
Description
-----------
In this PR:
* Update coverity version to 2023.6.1
* Replace CMake variable "UNIT_TESTS" with "UNITTEST", "COVERITY" with "COV_ANALYSIS" to align with FreeRTOS libraries
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Update coverity version message

- tools/cmock.cmake
- tools/mbedtls.cmake
- tools/unity.cmake
Description
-----------
* Update Mbedtls 3 to v3.6.0 LTS
* Update Mbedtls 2 to v2.28.8
* Update CMock to v2.5.3
* Update Unity to v2.6.0
Test Steps
-----------
N/A
Checklist:
----------
Related Issue
-----------
> Update submodule version

- source/portable/mbedtls/core_pkcs11_mbedtls.c
- test/pkcs11_mbedtls_utest/core_pkcs11_mbedtls_utest.c
Description
-----------
This PR address the issue #170 to fix mbedtls C_GetAttributeValue implementation
* ulValueLen is set to CK_UNAVAILABLE_INFORMATION if the attributes for the object can't be obtained.
* Attributes in the templates will be processed when error codes are CKR_ATTRIBUTE_SENSITIVE, CKR_ATTRIBUTE_TYPE_INVALID, or CKR_BUFFER_TOO_SMALL.
Reference [PKCS11-base-v2.40](http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.doc)
Test Steps
-----------
Verify in the unit test.
Checklist:
----------
Related Issue
-----------
#170 
> Fix mbedtls c get attribute value

- docs/doxygen/include/size_table.md
- source/core_pkcs11.c
- test/wrapper_utest/core_pkcs11_utest.c
Description
-----------
Add more unit test to cover code_pkcs11.c
In this PR:
* Code coverage for core_pkcs11.c is now 100%
* Remove local function `prvOpenSession` since it is only used in `xInitializePkcs11Session` and `pxFunctionList` is already obtained in this function.
* Remove redundant functional pointer check in `xInitializePkcs11Token`.
* Add more `C_GetFunctionList` check
Test Steps
-----------
N/A
Checklist:
----------
Related Issue
-----------
> Add more unit test to cover code_pkcs11.c

- .github/workflows/ci.yml
- docs/doxygen/include/size_table.md
- source/portable/mbedtls/core_pkcs11_mbedtls.c
- test/pkcs11_mbedtls_utest/core_pkcs11_mbedtls_utest.c
- test/wrapper_utest/core_pkcs11_utest.c
Description
-----------
Add more unit test to cover code_pkcs11.c
In this PR:
* Increase line coverage for core_pkcs11_mbedtls.c to 100%
* Update CI line coverage threshold to 100 and branch coverage threshold to 92
* Fix compiler warning in unit test
Test Steps
-----------
N/A
Checklist:
----------
Related Issue
-----------
> Add more unit test for core_pkcs11_mbedtls.c

- .github/.cSpellWords.txt
- README.md
- docs/doxygen/include/size_table.md
- source/portable/mbedtls/core_pkcs11_mbedtls.c
- test/mbedtls_integration/mbedtls_integration_test.c
- test/pkcs11_mbedtls_utest/core_pkcs11_mbedtls_utest.c
- tools/coverity/README.md
Description
-----------
Presently the library is not able to support TLSv1.3, this is because it does not allow exporting RSA public attributes. It does not populate the attribute values for an RSA key using the `mbedtls_rsa_context` due to which the certificate verification fails. 
This PR adds a new function that populates attribute values for an RSA key from the mbed TLS context.
Test Steps
-----------
For now it is only tested using the the corePKCS MQTT Mutual Auth Demo that builds with the changes and is able to create a successful TLS connection with the broker. 
Checklist:
----------
Related Issue
-----------
> Populate RSA key from mbedtls context to support TLSv1.3

- .github/workflows/ci.yml
- tools/mbedtls.cmake
- tools/mbedtls_configure.sh
Description
-----------
This PR upgrades the mbedtls versions to v2.28.10 and v3.6.3. 
Test Steps
-----------
The unit tests and integration tests are all passing after this change.
Checklist:
----------
> Update mbedtls version and fix build errors
