FreeRTOS/corePKCS11

- .github/workflows/ci.yml
- .gitmodules
- README.md
- test/unit-test/CMakeLists.txt
- test/unit-test/cmock_build.cmake
Update submodules to git submodule checkout method so they aren't cloned in hub repos.
> Submodule update

- .gitmodules
Indentation fixes in .gitmodules
> Indentation fixes in .gitmodules

- .gitmodules
- source/core_pki_utils.c
- source/include/core_pki_utils.h
- test/cbmc/.gitignore
- test/cbmc/include/README.md
- test/cbmc/proofs/Makefile-project-defines
- test/cbmc/proofs/Makefile-project-targets
- test/cbmc/proofs/Makefile-project-testing
- test/cbmc/proofs/Makefile-template-defines
- test/cbmc/proofs/Makefile.common
- test/cbmc/proofs/PKI_mbedTLSSignatureToPkcs11Signature/Makefile
- test/cbmc/proofs/PKI_mbedTLSSignatureToPkcs11Signature/PKI_mbedTLSSignatureToPkcs11Signature_harness.c
- test/cbmc/proofs/PKI_mbedTLSSignatureToPkcs11Signature/README.md
- test/cbmc/proofs/PKI_mbedTLSSignatureToPkcs11Signature/cbmc-proof.txt
- test/cbmc/proofs/PKI_mbedTLSSignatureToPkcs11Signature/cbmc-viewer.json
- test/cbmc/proofs/README.md
- test/cbmc/proofs/prepare.py
- test/cbmc/proofs/run-cbmc-proofs.py
- test/cbmc/sources/README.md
- test/cbmc/stubs/README.md
* Add CBMC common layer
* Add proof for PKI_mbedTLSSignatureToPkcs11Signature
> Add CBMC and first CBMC proof

- source/core_pkcs11.c
- test/cbmc/proofs/Makefile-project-defines
- test/cbmc/proofs/config/core_pkcs11_config.h
- test/cbmc/proofs/xGetSlotList/Makefile
- test/cbmc/proofs/xGetSlotList/README.md
- test/cbmc/proofs/xGetSlotList/cbmc-proof.txt
- test/cbmc/proofs/xGetSlotList/cbmc-viewer.json
- test/cbmc/proofs/xGetSlotList/xGetSlotList_harness.c
- test/unit-test/core_pkcs11_utest.c
> CBMC: xGetSlotList

- MISRA.md
- tools/coverity/misra.config
Running MISRA on the POSIX port led to some more errors that need to be ignored.
> MISRA Update from POSIX port

- source/portable/mbedtls/core_pkcs11_mbedtls.c
- test/cbmc/proofs/C_CloseSession/C_CloseSession_harness.c
- test/cbmc/proofs/C_CloseSession/Makefile
- test/cbmc/proofs/C_CloseSession/README.md
- test/cbmc/proofs/C_CloseSession/cbmc-proof.txt
- test/cbmc/proofs/C_CloseSession/cbmc-viewer.json
- test/cbmc/proofs/C_GenerateRandom/C_GenerateRandom_harness.c
- test/cbmc/proofs/C_GenerateRandom/Makefile
- test/cbmc/proofs/C_GenerateRandom/README.md
- test/cbmc/proofs/C_GenerateRandom/cbmc-proof.txt
- test/cbmc/proofs/C_GenerateRandom/cbmc-viewer.json
- test/cbmc/proofs/C_OpenSession/C_OpenSession_harness.c
- test/cbmc/proofs/C_OpenSession/Makefile
- test/cbmc/proofs/C_OpenSession/README.md
- test/cbmc/proofs/C_OpenSession/cbmc-proof.txt
- test/cbmc/proofs/C_OpenSession/cbmc-viewer.json
- test/cbmc/stubs/mbedtls_stubs.c
* CBMC proof for C_OpenSession
* CBMC proof for C_CloseSession
* CBMC proof for C_GenerateRandom
> CMBC: Proofs for sessions and RNG

- .github/workflows/ci.yml
- CONTRIBUTING.md
- MISRA.md
- Update github actions to run on PRs just to main.
- Update CONTRIBUTING.md to reference the main branch.
- Reference the main branch in the CSDK.
Other references are to the FreeRTOS/FreeRTOS repo which is out of scope.
> Update all relevant master to main references.

- test/cbmc/proofs/C_GetFunctionList/C_GetFunctionList_harness.c
- test/cbmc/proofs/C_GetFunctionList/Makefile
- test/cbmc/proofs/C_GetFunctionList/README.md
- test/cbmc/proofs/C_GetFunctionList/cbmc-proof.txt
- test/cbmc/proofs/C_GetFunctionList/cbmc-viewer.json
- test/cbmc/proofs/C_GetMechanismInfo/C_GetMechanismInfo_harness.c
- test/cbmc/proofs/C_GetMechanismInfo/Makefile
- test/cbmc/proofs/C_GetMechanismInfo/README.md
- test/cbmc/proofs/C_GetMechanismInfo/cbmc-proof.txt
- test/cbmc/proofs/C_GetMechanismInfo/cbmc-viewer.json
- test/cbmc/proofs/C_GetSlotList/C_GetSlotList_harness.c
- test/cbmc/proofs/C_GetSlotList/Makefile
- test/cbmc/proofs/C_GetSlotList/README.md
- test/cbmc/proofs/C_GetSlotList/cbmc-proof.txt
- test/cbmc/proofs/C_GetSlotList/cbmc-viewer.json
Added CBMC proofs for:
* C_GetFunctionList
* C_GetSlotList
* C_GetMechanismInfo
> CBMC proofs

- source/portable/mbedtls/core_pkcs11_mbedtls.c
- test/cbmc/proofs/C_FindObjects/C_FindObjects_harness.c
- test/cbmc/proofs/C_FindObjects/Makefile
- test/cbmc/proofs/C_FindObjects/README.md
- test/cbmc/proofs/C_FindObjects/cbmc-proof.txt
- test/cbmc/proofs/C_FindObjects/cbmc-viewer.json
- test/cbmc/proofs/C_FindObjectsFinal/C_FindObjectsFinal_harness.c
- test/cbmc/proofs/C_FindObjectsFinal/Makefile
- test/cbmc/proofs/C_FindObjectsFinal/README.md
- test/cbmc/proofs/C_FindObjectsFinal/cbmc-proof.txt
- test/cbmc/proofs/C_FindObjectsFinal/cbmc-viewer.json
- test/cbmc/proofs/C_FindObjectsInit/C_FindObjectsInit_harness.c
- test/cbmc/proofs/C_FindObjectsInit/Makefile
- test/cbmc/proofs/C_FindObjectsInit/README.md
- test/cbmc/proofs/C_FindObjectsInit/cbmc-proof.txt
- test/cbmc/proofs/C_FindObjectsInit/cbmc-viewer.json
- test/cbmc/stubs/core_pkcs11_pal_stubs.c
- test/cbmc/stubs/mbedtls_stubs.c
* CBMC proof for C_FindObjectsInit
* CBMC proof for C_FindObjects
* CBMC proof for C_FindObjectsFinal
> CBMC: three proofs

- CHANGELOG.md
Updates highlight points of difference between December release and September release.
> Update changelog for December release

- docs/doxygen/pages.dox
Update memory estimates for corePKCS11.
> Update memory estimates for corePKCS11

- docs/doxygen/include/size_table.html
This updates the memory estimates table to include the data section.
> Update memory estimates

- README.md
Update to latest C-SDK release URL.
> Update memory requirements link.

- source/core_pkcs11.c
- test/unit-test/core_pkcs11_utest.c
Reported in https://github.com/FreeRTOS/corePKCS11/issues/87.
> Fix potential double free in core_pkcs11.c

- lexicon.txt
- source/portable/posix/core_pkcs11_pal.c
- source/portable/windows/core_pkcs11_pal.c
- test/system-test/system-tests/pkcs11_system_test.c
- tools/cmock/coverage.cmake
> Spelling fixes

- README.md
- docs/doxygen/include/size_table.html
- source/portable/mbedtls/core_pkcs11_mbedtls.c
- test/cbmc/proofs/C_Verify/Makefile
- test/system-test/system-tests/pkcs11_system_test.c
- test/unit-test/core_pkcs11_mbedtls_utest.c
Support for verifying a SHA256-HMAC signature.
> Feature: Add support for SHA256-HMAC Verify

- docs/doxygen/include/size_table.html
- source/portable/mbedtls/core_pkcs11_mbedtls.c
- test/system-test/system-tests/pkcs11_system_test.c
- test/unit-test/core_pkcs11_mbedtls_utest.c
Adds feature support for SHA256-HMAC signatures. 
Updated unit tests and system tests to confirm integration.
> Feature: SHA256-HMAC sign

- docs/doxygen/include/size_table.html
- lexicon.txt
- source/include/core_pkcs11.h
- source/portable/mbedtls/core_pkcs11_mbedtls.c
- test/system-test/system-tests/pkcs11_system_test.c
- test/system-test/test-config/core_test_pkcs11_config.h
- test/system-test/test-config/mbedtls_config.h
- test/unit-test/CMakeLists.txt
- test/unit-test/config/aws_mbedtls_config.h
- test/unit-test/core_pkcs11_mbedtls_utest.c
> AES CMAC - VerifyInit/Verify

- docs/doxygen/include/size_table.html
- source/portable/mbedtls/core_pkcs11_mbedtls.c
- test/system-test/system-tests/pkcs11_system_test.c
- test/unit-test/core_pkcs11_mbedtls_utest.c
> AES CMAC Sign/SignInit

- source/portable/mbedtls/core_pkcs11_mbedtls.c
This PR resolves recent regressions for MISRA.
> Minor MISRA fixes.

- source/portable/os/freertos_winsim/core_pkcs11_pal.c
core_pkcs11_pal.c changes missing from the earlier PR raised to commonize the code (https://github.com/FreeRTOS/corePKCS11/pull/123)
> core_pkcs11_pal.c changes missing

- tools/coverity/README.md
The README.md file gives detailed instruction on creating MISRA violation report on library sources files.
> Added README.md to tools/coverity/

- .github/workflows/ci.yml
Update ci.yml with the following changes:
* Switch to shared gnu complexity action, increase threshold.
* Updated to latest versions of checkout and setup-python
* Enable codecov reporting
* Archive unit test results
> Update ci jobs
